<?php

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function signIn($username, $password)
    {
        $dql = "SELECT count(u) FROM User u WHERE u.name = $username AND u.password = $password";

        $this->createQueryBuilder('u')->select('u')->from('User', 'u')->andWhere('u.name = '.$username);
    }
}
